export const NFTItems = [
  {
    name: "Honeycomb",
    image: "/nft/honeycomb.svg",
    new: false,
    soon: false,
    link: "https://magiceden.io/collections/berachain/honey-comb-106",
  },
  {
    name: "Honey Jar (Gen 1)",
    image: "/nft/gen1.svg",
    new: false,
    soon: false,
    link: "https://app.0xhoneyjar.xyz/mint/berasvsapes",
  },
  {
    name: "Honey Jar (Gen 2)",
    image: "/nft/gen2.svg",
    new: false,
    soon: false,
    link: "https://app.0xhoneyjar.xyz/mint/miladysandberas",
  },
  {
    name: "Honey Jar (Gen 3)",
    image: "/nft/gen3.svg",
    new: false,
    soon: false,
    link: "https://app.0xhoneyjar.xyz/mint/pudgyfrens",
  },
  {
    name: "Honey Jar (Gen 4)",
    image: "/nft/gen4.svg",
    new: false,
    soon: false,
    link: "https://app.0xhoneyjar.xyz/mint/triforcebees",
  },
  {
    name: "Honey Jar (Gen 5)",
    image: "/nft/gen5.svg",
    new: false,
    soon: false,
    link: "https://app.0xhoneyjar.xyz/mint/gen5",
  },
  {
    name: "Honey Jar (Gen 6)",
    image: "/nft/gen6.svg",
    new: true,
    soon: false,
    link: "https://app.0xhoneyjar.xyz/mint/gen6",
  },
];
