#!/usr/bin/env bash
# =============================================================================
# overlay-source-helper.sh — cycle-099 Sprint 2C (T2.5)
# =============================================================================
# Helper functions for sourcing `.run/merged-model-aliases.sh` (the cycle-099
# Sprint 2B output) into a bash adapter's environment, with version-mismatch
# detection per Brief E.
#
# The merged file is generated by `.claude/scripts/lib/model-overlay-hook.py`
# on demand. When present and valid, it exposes five associative arrays
# (LOA_MODEL_PROVIDERS, LOA_MODEL_IDS, LOA_MODEL_ENDPOINT_FAMILIES,
# LOA_MODEL_COST_INPUT_PER_MTOK, LOA_MODEL_COST_OUTPUT_PER_MTOK) that include
# both framework defaults AND operator-added entries from
# `.loa.config.yaml::model_aliases_extra`. This is the operator-extras-aware
# resolution path, complementing the framework-only `model-resolver.sh`.
#
# Usage in a caller (e.g. `model-adapter.sh`):
#
#     # shellcheck source=lib/overlay-source-helper.sh
#     source "$SCRIPT_DIR/lib/overlay-source-helper.sh"
#     loa_overlay_init || true   # best-effort; framework resolver still works
#
#     # ... later, in the resolution chain:
#     if model_id="$(loa_overlay_resolve_provider_id "$alias" 2>/dev/null)"; then
#         : # operator-extras-aware path won
#     elif model_id="$(resolve_provider_id "$alias" 2>/dev/null)"; then
#         : # framework path won
#     ...
#
# Design constraints:
#   - Best-effort: if the merged file is missing or unreadable, the caller
#     falls through to existing resolution paths. We do NOT exit on init
#     failure — bash adapters that ran fine pre-cycle-099 must keep working.
#   - Defense-in-depth: bash syntax check (`bash -n`) before sourcing, in
#     case the file was tampered with after the hook's atomic-write.
#   - Shared flock briefly held during the read (matches cycle-099 SDD §6.3.1
#     loader contract: shared lock during multi-file reads avoids torn-read
#     racing against the writer's exclusive lock).
#   - Version-mismatch detection: caller can call loa_overlay_refresh_if_stale
#     between operations to pick up cross-process regen.
# =============================================================================

# Strict mode is the caller's choice; we don't enforce it because some legacy
# scripts source us under `set +e` and we shouldn't surprise them.

_OVERLAY_HELPER_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_OVERLAY_HELPER_REPO_ROOT="$(cd "$_OVERLAY_HELPER_LIB_DIR/../../.." && pwd)"
_OVERLAY_HELPER_HOOK="$_OVERLAY_HELPER_LIB_DIR/model-overlay-hook.py"

# Path resolution. Operators may override via env var for non-standard layouts
# (e.g., LOA_GRIMOIRE_DIR-style configurability). The override is honored
# unconditionally because the file's content is shell-syntax-checked before
# sourcing — there's no trust escalation surface.
_OVERLAY_HELPER_MERGED="${LOA_OVERLAY_MERGED:-$_OVERLAY_HELPER_REPO_ROOT/.run/merged-model-aliases.sh}"
_OVERLAY_HELPER_LOCKFILE="${LOA_OVERLAY_LOCKFILE:-${_OVERLAY_HELPER_MERGED}.lock}"

# loa_overlay_read_version <file?> — read the `# version=N` header line from
# the merged file. Echoes the integer on success; returns 1 + empty stdout
# on missing file or unparseable header.
loa_overlay_read_version() {
    local file="${1:-$_OVERLAY_HELPER_MERGED}"
    [[ -f "$file" ]] || return 1
    local v
    # Read only the first 10 lines (the header is always at the top); avoid
    # scanning the entire file every call. Match `# version=<digits>` only.
    v="$(head -10 "$file" 2>/dev/null | sed -n 's/^# version=\([0-9][0-9]*\)[[:space:]]*$/\1/p' | head -1)"
    [[ -n "$v" ]] || return 1
    printf '%s' "$v"
}

# loa_overlay_read_source_sha <file?> — read the source-sha256 header. Used
# for cache-validity checks (e.g., cross-validating against a fresh input
# hash). Echoes the 64-char lowercase hex digest on success; returns 1 on
# missing file or unparseable header.
loa_overlay_read_source_sha() {
    local file="${1:-$_OVERLAY_HELPER_MERGED}"
    [[ -f "$file" ]] || return 1
    local s
    s="$(head -10 "$file" 2>/dev/null | sed -n 's/^# source-sha256=\([0-9a-f][0-9a-f]*\)[[:space:]]*$/\1/p' | head -1)"
    [[ -n "$s" && ${#s} -eq 64 ]] || return 1
    printf '%s' "$s"
}

# _loa_overlay_invoke_hook — invoke the Sprint 2B hook to (re)generate
# the merged file. Best-effort: returns 0 on hook success, 1 on any failure
# (missing python3, missing hook, hook exit non-zero). Caller decides
# whether to retry or fall through.
_loa_overlay_invoke_hook() {
    [[ -f "$_OVERLAY_HELPER_HOOK" ]] || return 1
    command -v python3 &>/dev/null || return 1
    # Suppress stderr — operator-facing diagnostics are emitted by the
    # hook's own structured-marker channel; we don't want to leak them
    # into adapter output streams. If callers need the diagnostic, they
    # can invoke the hook directly.
    python3 "$_OVERLAY_HELPER_HOOK" 2>/dev/null
}

# _loa_overlay_source_under_lock — source the merged file with a brief
# shared flock acquisition (matches SDD §6.3.4 multi-file-read contract).
# Falls back to plain `source` if flock(1) is unavailable (e.g., macOS
# without util-linux).
_loa_overlay_source_under_lock() {
    local file="$1"
    if command -v flock &>/dev/null && [[ -f "$_OVERLAY_HELPER_LOCKFILE" ]]; then
        local fd
        # Use a high fd to avoid clashing with caller's redirections.
        exec 9< "$_OVERLAY_HELPER_LOCKFILE"
        if flock -s -w 5 9 2>/dev/null; then
            # shellcheck source=/dev/null
            source "$file"
            local rc=$?
            flock -u 9 2>/dev/null || true
            exec 9<&-
            return $rc
        fi
        exec 9<&-
    fi
    # No flock available, or lockfile missing — source directly. The hook
    # uses atomic-rename, so a partial-file read is impossible regardless
    # of whether we hold the shared lock. The lock matters mostly to
    # serialize against a concurrent regen finishing mid-source.
    # shellcheck source=/dev/null
    source "$file"
}

# loa_overlay_init — ensure the merged file exists, source it, capture
# the in-memory version. After successful init:
#   - LOA_MODEL_PROVIDERS / LOA_MODEL_IDS / LOA_MODEL_ENDPOINT_FAMILIES /
#     LOA_MODEL_COST_INPUT_PER_MTOK / LOA_MODEL_COST_OUTPUT_PER_MTOK
#     associative arrays are populated in the caller's shell
#   - LOA_OVERLAY_VERSION_AT_LOAD is set to the version integer
#   - LOA_OVERLAY_FINGERPRINT is set to the 12-char fingerprint
#
# Returns 0 on success; returns 1 if the merged file is unavailable AND
# the hook could not (re)generate it. Caller falls through to alternative
# resolution paths.
loa_overlay_init() {
    if [[ ! -f "$_OVERLAY_HELPER_MERGED" ]]; then
        # Try to generate via the hook. Best-effort.
        _loa_overlay_invoke_hook || return 1
    fi
    [[ -f "$_OVERLAY_HELPER_MERGED" ]] || return 1
    # Defense-in-depth: refuse to source content that isn't valid bash.
    # The hook's atomic-rename is supposed to guarantee this, but a
    # tampered-after-rename file would otherwise execute arbitrary code
    # via `source`.
    bash -n "$_OVERLAY_HELPER_MERGED" 2>/dev/null || return 1
    LOA_OVERLAY_VERSION_AT_LOAD="$(loa_overlay_read_version "$_OVERLAY_HELPER_MERGED")" || return 1
    _loa_overlay_source_under_lock "$_OVERLAY_HELPER_MERGED" || return 1
    return 0
}

# loa_overlay_refresh_if_stale — re-read the on-disk version header.
# If it differs from LOA_OVERLAY_VERSION_AT_LOAD, the file was rewritten
# (cross-process regen), so re-source. Returns 0 whether or not a refresh
# was performed; returns 1 only if a refresh was attempted and failed.
#
# This is mostly relevant for long-running processes that source the
# overlay once at startup. Short-lived bash adapters usually exit before
# drift becomes detectable, but the check is cheap (header read only)
# so adding it is a defense against future cross-process integrations.
loa_overlay_refresh_if_stale() {
    [[ -n "${LOA_OVERLAY_VERSION_AT_LOAD:-}" ]] || return 0
    local on_disk
    on_disk="$(loa_overlay_read_version "$_OVERLAY_HELPER_MERGED")" || return 0
    if [[ "$on_disk" != "$LOA_OVERLAY_VERSION_AT_LOAD" ]]; then
        loa_overlay_init || return 1
    fi
    return 0
}

# loa_overlay_resolve_provider_id <alias> — lookup the alias in the
# overlay's LOA_MODEL_* arrays and emit `provider:api_id`. Returns 0 +
# stdout on hit; returns 1 (silent) on miss.
#
# The caller's resolution chain typically tries this FIRST (operator
# extras win), then falls back to model-resolver.sh::resolve_provider_id
# (framework only) on miss.
loa_overlay_resolve_provider_id() {
    local alias="$1"
    [[ -n "$alias" ]] || return 1
    # Use array indirection guarded by `declare -p` to handle the case
    # where the array isn't populated (e.g., loa_overlay_init failed).
    if ! declare -p LOA_MODEL_PROVIDERS &>/dev/null; then
        return 1
    fi
    if ! declare -p LOA_MODEL_IDS &>/dev/null; then
        return 1
    fi
    local provider="${LOA_MODEL_PROVIDERS[$alias]:-}"
    local api_id="${LOA_MODEL_IDS[$alias]:-}"
    [[ -n "$provider" && -n "$api_id" ]] || return 1
    printf '%s:%s' "$provider" "$api_id"
}

# loa_overlay_resolve_alias <alias> — lookup just the alias→api_id mapping
# (without provider prefix). Mirrors model-resolver.sh::resolve_alias.
# Returns 0 + stdout on hit; returns 1 on miss.
loa_overlay_resolve_alias() {
    local alias="$1"
    [[ -n "$alias" ]] || return 1
    if ! declare -p LOA_MODEL_IDS &>/dev/null; then
        return 1
    fi
    local api_id="${LOA_MODEL_IDS[$alias]:-}"
    [[ -n "$api_id" ]] || return 1
    printf '%s' "$api_id"
}

# loa_overlay_resolve_endpoint_family <alias> — lookup the endpoint family
# (chat / responses / messages / converse) for an alias. Returns 0 +
# stdout on hit; returns 1 on miss. Used by callers that need to route
# differently (e.g., openai responses vs chat).
loa_overlay_resolve_endpoint_family() {
    local alias="$1"
    [[ -n "$alias" ]] || return 1
    if ! declare -p LOA_MODEL_ENDPOINT_FAMILIES &>/dev/null; then
        return 1
    fi
    local family="${LOA_MODEL_ENDPOINT_FAMILIES[$alias]:-}"
    [[ -n "$family" ]] || return 1
    printf '%s' "$family"
}
